### ISSUE TITLE
azure vm docker create: --location option will be ignored

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#1355]
```sh
$  azure vm docker create -z large -e 22 -s SUBSID -l 'West US' HSNAME b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_04-LTS-amd64-server-20140724-en-us-30GB azureuser 'PA$$W0RD!'
info:    Executing command vm docker create
info:    Found docker certificates.
+ Looking up image b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_04-LTS-amd64-server-20140724-en-us-30GB
+ Looking up cloud service
info:    cloud service HSNAME not found.
+ Creating cloud service
+ Retrieving storage accounts
+ Looking up cloud service
warn:    --location option will be ignored
+ Getting cloud service properties
+ Looking up deployment
+ Creating VM
info:    OK
info:    vm docker create command OK
```

the `warn:    --location option will be ignored` line is a bit concerning. It is not ignored and the command uses that option correctly to create the VM however prints this anyway.

**Comment by BretFisher** [comment]
Note this happens with `azure vm create` as well, so not exclusive to `docker`. v0.8.15

**Comment by ahmetalpbalkan** [comment]
@babumuralidharan is this fixed? Please do not close until you publish the fix publicly. I don't think moving to an internal work item tracker should close the issue here. People are still hitting this. This should remain open.

**Comment by babumuralidharan** [comment]
@ahmetalpbalkan, we are prioritizing this issue and i have just opened this issue here.

**Comment by hopetobelievein** [comment]
Fixed in MSOpenTech/dev branch, Will be part of PR from MSOpenTech.

**Comment by kmouss** [comment]
This fixed and will be part of next release

**Comment by ahmetalpbalkan** [comment]
@kmouss did we have a new release since Feb 24? I now run 0.8.17 and I still get this error while trying to create a VM that already exists with that name.

**Comment by ahmetalpbalkan** [comment]
looks like this is fixed (mostly)

however the warning still gets printed if the cloud service name was taken:

```
➜  ~  azure vm create -e -l 'Southeast Asia' ahmetb-test2 b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_10-amd64-server-20141020-en-us-30GB  azureuser 'myPa$$w0rd'
info:    Executing command vm create
warn:    --vm-size has not been specified. Defaulting to "Small".
+ Looking up image b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_10-amd64-server-20141020-en-us-30GB
+ Looking up cloud service
warn:    --location option will be ignored
+ Getting cloud service properties
+ Looking up deployment
help:    Specify --connect option to connect the new VM to an existing VM
error:   A VM with dns prefix "ahmetb-test2" already exists
error:   vm create command failed

➜  ~  azure -v
0.9.5
```

if it's not taken, `--location option will be ignored` doesn't get printed. 

Can you please take a look folks?

**Comment by sauryadas** [comment]
@amarzavery This is not IAAS. Can you please create a docker label and assign?

**Comment by ahmetalpbalkan** [comment]
@sauryadas @amarzavery we should discuss about phasing out and retiring `azure vm docker` commands. We mostly aim to keep `docker-machine` azure driver around for this task or the `azure vm create`+`azure vm extension set DockerExtension` command to do the same task.

Investing in this subcommand does not make much sense. Feel free to close this issue.
