### ISSUE TITLE
ASM: azure network vnet list command has issues

### ISSUE THREAD

**Issue by infosatheesh2020** [Azure/azure-xplat-cli#2143]
Listing VNET using CLI shows below errors:

#azure network vnet list
info:    Executing command network vnet list
+ Looking up the virtual network sites                                         
error:   Cannot read property 'vpnGatewayAddress' of undefined
info:    Error information has been recorded to /home/samanoha/.azure/azure.err
error:   network vnet list command failed

[samanoha@crystal Downloads]$ cat /home/samanoha/.azure/azure.err
Mon Sep 28 2015 12:08:30 GMT+0300 (EEST):
{ [TypeError: Cannot read property 'vpnGatewayAddress' of undefined]
  stack: [Getter/Setter],
  __frame: 
   { name: 'list__2',
     line: 91,
     file: '/usr/lib/node_modules/azure-cli/lib/commands/asm/network/virtualNetwork._js',
     prev: 
      { name: '__7',
        line: 132,
        file: '/usr/lib/node_modules/azure-cli/lib/commands/asm/network/network._js',
        prev: undefined,
        calls: 1,
        active: false,
        offset: 4,
        col: 21 },
     calls: 1,
     active: true,
     offset: 3,
     col: 25 },
  rawStack: [Getter] }
TypeError: Cannot read property 'vpnGatewayAddress' of undefined
  <<< async stack >>>
  at list__2 (/usr/lib/node_modules/azure-cli/lib/commands/asm/network/virtualNetwork._js:94:26)
  at __7 (/usr/lib/node_modules/azure-cli/lib/commands/asm/network/network._js:136:22)
  <<< raw stack >>>
    at /usr/lib/node_modules/azure-cli/lib/commands/asm/network/virtualNetwork._js:116:58
    at /usr/lib/node_modules/azure-cli/lib/util/logging.js:114:38
    at Array.forEach (native)
    at Object.log.table (/usr/lib/node_modules/azure-cli/lib/util/logging.js:114:12)
    at /usr/lib/node_modules/azure-cli/lib/commands/asm/network/virtualNetwork._js:107:25
    at Interactor.__.extend.formatOutput (/usr/lib/node_modules/azure-cli/lib/util/interaction._js:268:7)
    at ___ (/usr/lib/node_modules/azure-cli/lib/commands/asm/network/virtualNetwork._js:102:26)
    at ___ (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:111:13)
    at ___ (/usr/lib/node_modules/azure-cli/lib/commands/asm/network/virtualNetwork._js:283:17)
    at __tryCatch (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:150:4)

[samanoha@crystal Downloads]$ node -v
v0.10.36
[samanoha@crystal Downloads]$ azure -v
0.9.9
[samanoha@crystal Downloads]$ cat /etc/fedora-release 
Fedora release 22 (Twenty Two)

**Comment by romangromov** [comment]
Hi @infosatheesh2020, can you please attach output for `azure network vnet list --json` command?

**Comment by infosatheesh2020** [comment]
@romangromov I have sent the info to your email

**Comment by romangromov** [comment]
@infosatheesh2020 thanks, it's a bug, will fix

**Comment by infosatheesh2020** [comment]
Thank you @romangromov

**Comment by romangromov** [comment]
@infosatheesh2020 fix merged to `dev`, will be available on next release

**Comment by yugangw-msft** [comment]
The change has been integrated to release-0.9.10

**Comment by ronaldmendoza** [comment]
I'm still seeing this error in release-0.9.10

$ azure network vnet list -vv
info:    Executing command network vnet list
verbose: Looking up the virtual network sites
silly:   requestOptions
silly:   {
silly:       rawResponse: false,
silly:       queryString: {},
silly:       method: 'GET',
silly:       headers: { user-agent: 'WindowsAzureXplatCLI/0.9.10', x-ms-version: '2015-04-01' },
silly:       url: 'https://management.core.windows.net/[deleted]/services/networking/virtualnetwork'
silly:   }
silly:   returnObject
silly:   {
silly:       statusCode: 200,
silly:       header: {
silly:           content-type: 'application/xml; charset=utf-8',
silly:           x-ms-request-id: '[deleted]',
silly:           cache-control: 'no-cache',
silly:           server: '1.0.6198.280 (rd_rdfe_stable.151023-1048) Microsoft-HTTPAPI/2.0',
silly:           date: 'Fri, 30 Oct 2015 00:31:06 GMT',
silly:           strict-transport-security: 'max-age=31536000; includeSubDomains',
silly:           content-length: '1976',
silly:           x-ms-servedbyregion: 'ussouth3'
silly:       },


[ stuff deleted ]
error:   Cannot read property 'vpnGatewayAddress' of undefined
silly:   {
silly:       stack: "TypeError: Cannot read property 'vpnGatewayAddress' of undefined\n  <<< async stack >>>\n  at list__2 (/usr/local/lib/node_modules/azure-cli/lib/commands/asm/network/virtualNetwork._js:94:26)\n  at __7 (/usr/local/lib/node_modules/azure-cli/lib/commands/asm/network/network._js:136:22)\n  <<< raw stack >>>\n    at /usr/local/lib/node_modules/azure-cli/lib/commands/asm/network/virtualNetwork._js:116:58\n    at /usr/local/lib/node_modules/azure-cli/lib/util/logging.js:116:38\n    at Array.forEach (native)\n    at Object.log.table (/usr/local/lib/node_modules/azure-cli/lib/util/logging.js:116:12)\n    at /usr/local/lib/node_modules/azure-cli/lib/commands/asm/network/virtualNetwork._js:107:25\n    at Interactor.__.extend.formatOutput (/usr/local/lib/node_modules/azure-cli/lib/util/interaction._js:268:7)\n    at ___ (/usr/local/lib/node_modules/azure-cli/lib/commands/asm/network/virtualNetwork._js:102:26)\n    at ___ (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:111:13)\n    at ___ (/usr/local/lib/node_modules/azure-cli/lib/commands/asm/network/virtualNetwork._js:283:17)\n    at __tryCatch (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:150:4)\n",
silly:       arguments: [ 'vpnGatewayAddress', undefined ],
silly:       type: 'non_object_property_load',
silly:       message: "Cannot read property 'vpnGatewayAddress' of undefined",
silly:       __frame: {
silly:           name: 'list__2',
silly:           line: 91,
silly:           file: '/usr/local/lib/node_modules/azure-cli/lib/commands/asm/network/virtualNetwork._js',
silly:           prev: {
silly:               name: '__7',
silly:               line: 132,
silly:               file: '/usr/local/lib/node_modules/azure-cli/lib/commands/asm/network/network._js',
silly:               prev: undefined,
silly:               calls: 1,
silly:               active: false,
silly:               offset: 4,
silly:               col: 21
silly:           },
silly:           calls: 1,
silly:           active: true,
silly:           offset: 3,
silly:           col: 25
silly:       },
silly:       rawStack: "TypeError: Cannot read property 'vpnGatewayAddress' of undefined\n    at /usr/local/lib/node_modules/azure-cli/lib/commands/asm/network/virtualNetwork._js:116:58\n    at /usr/local/lib/node_modules/azure-cli/lib/util/logging.js:116:38\n    at Array.forEach (native)\n    at Object.log.table (/usr/local/lib/node_modules/azure-cli/lib/util/logging.js:116:12)\n    at /usr/local/lib/node_modules/azure-cli/lib/commands/asm/network/virtualNetwork._js:107:25\n    at Interactor.__.extend.formatOutput (/usr/local/lib/node_modules/azure-cli/lib/util/interaction._js:268:7)\n    at ___ (/usr/local/lib/node_modules/azure-cli/lib/commands/asm/network/virtualNetwork._js:102:26)\n    at ___ (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:111:13)\n    at ___ (/usr/local/lib/node_modules/azure-cli/lib/commands/asm/network/virtualNetwork._js:283:17)\n    at __tryCatch (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:150:4)\n"
silly:   }
info:    Error information has been recorded to /home/mfadmin/.azure/azure.err
verbose: TypeError: Cannot read property 'vpnGatewayAddress' of undefined
  <<< async stack >>>
  at list__2 (/usr/local/lib/node_modules/azure-cli/lib/commands/asm/network/virtualNetwork._js:94:26)
  at __7 (/usr/local/lib/node_modules/azure-cli/lib/commands/asm/network/network._js:136:22)
  <<< raw stack >>>
    at /usr/local/lib/node_modules/azure-cli/lib/commands/asm/network/virtualNetwork._js:116:58
    at /usr/local/lib/node_modules/azure-cli/lib/util/logging.js:116:38
    at Array.forEach (native)
    at Object.log.table (/usr/local/lib/node_modules/azure-cli/lib/util/logging.js:116:12)
    at /usr/local/lib/node_modules/azure-cli/lib/commands/asm/network/virtualNetwork._js:107:25
    at Interactor.__.extend.formatOutput (/usr/local/lib/node_modules/azure-cli/lib/util/interaction._js:268:7)
    at ___ (/usr/local/lib/node_modules/azure-cli/lib/commands/asm/network/virtualNetwork._js:102:26)
    at ___ (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:111:13)
    at ___ (/usr/local/lib/node_modules/azure-cli/lib/commands/asm/network/virtualNetwork._js:283:17)
    at __tryCatch (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:150:4)

error:   network vnet list command failed

**Comment by romangromov** [comment]
@ronaldmendoza can you please send me output JSON for `azure network vnet list` command? v-rogrom@microsoft.com
