### ISSUE TITLE
template list command missing api version

### ISSUE THREAD

**Issue by johndehavilland** [Azure/azure-xplat-cli#2169]
The command
>azure group template list

throws the following error:
>Missing api version query string.

This is with azure cli v. 0.9.9

**Comment by dlepow** [comment]
I just hit this error too.

**Comment by yugangw-msft** [comment]
@vivsriaus, please investigate.

**Comment by squillace** [comment]
+1. help doesn't even specify an api switch:

```
azure group template list --help                                                                                                                                                                                                                                                                                                            help:    Lists gallery resource group templates
help:
help:    Usage: group template list [options]
help:
help:    Options:
help:      -h, --help                     output usage information
help:      -v, --verbose                  use verbose output
help:      -vv                            more verbose with debug output
help:      --json                         use json output
help:      -c --category [category]       the category of the templates to list
help:      -p --publisher [publisher]     the publisher of the templates to list
help:      --subscription <subscription>  the Azure subscription to run against
help:
help:    Current Mode: arm (Azure Resource Management)
```

**Comment by simonsabin** [comment]
Getting the same error with the Powershell cmdlets 
https://social.msdn.microsoft.com/Forums/azure/en-US/1a5a32c8-3975-4c3e-afae-8797dba2af36/getazureresourcegroupgallerytemplate-error-missing-api-version-query-string-allowed-values-are?forum=windowsazuremanagement

**Comment by yugangw-msft** [comment]
We are actively working with the service team to get sdk and cmdlets fixed in the upcoming release.Will post further updates

**Comment by simonsabin** [comment]
Hi Yugangw-msft

Is it the same problem across all the affected cmdlets. Is the release likely to be this week? Is there a work around?

**Comment by yugangw-msft** [comment]
Addressed by #2176. Please check out the comments in the PR for the adjustment we had to make in the cmdlets because the new service api-version introduced breaking change.
This will be released out in the next couple of days with release-0.9.10

**Comment by mohitarora** [comment]
+1 I also encountered the same error.

**Comment by Rowdster** [comment]
This was closed, but I am still having this issue.  What was the fix?

**Comment by yugangw-msft** [comment]
@Rowdster, what was the azure-cli version in your box? 
Please have at least 0.9.10. You can run "azure -v" to check out the version

**Comment by Rowdster** [comment]
yugangw-msft, thanks.  I was at 0.9.9
