### ISSUE TITLE
Azure site command no longer exists in latest cli.

### ISSUE THREAD

**Issue by niemyjski** [Azure/azure-xplat-cli#3245]
> azure site deploymentscript --node

`Azure site` command no longer exists as shown here: https://github.com/projectkudu/kudu/wiki/Custom-Deployment-Script

I looked through the docs and there doesn't seem to be a way to generate it using the latest cli

**Comment by cephalin** [comment]
Change the CLI mode to ASM using `azure config mode asm`. I'm not sure when exactly the default CLI mode changed from ASM to ARM but it's at least a couple of months ago.

**Comment by eduardkoller** [comment]
@niemyjski - does this answer your question? Do you need more assistance?

**Comment by niemyjski** [comment]
Yes, that fixes it, it wasn't clear at all via the help docs or the wiki for this. May I suggest updating the cli to detect commands that are in one mode and not the other and have error output written that lets you know it's available in a different mode.

**Comment by niemyjski** [comment]
I was just going to edit the wiki to talk about this: https://github.com/projectkudu/kudu/wiki/Custom-Deployment-Script but it's locked :( (the community can't help you improve the docs).

**Comment by niemyjski** [comment]
Could someone add a quick note about the mode

**Comment by jsgoupil** [comment]
There are so many tutorials and pages that talk about `azure site` but definitely not to set this config from `arm` to `asm`. This was complicated to get it working. I had to go on npmjs, find this github page, then search for `deploymentscript` then search in issues... Way too complicated.

**Comment by amarzavery** [comment]
It is documented in the README.md of this repo over [here](https://github.com/Azure/azure-xplat-cli#2-modes). When you search the package "azure-cli" on npm, this info is also present over [there](https://www.npmjs.com/package/azure-cli#2-modes).

**Comment by jsgoupil** [comment]
@amarzavery Thank you for pointing about mode. But when you follow one of the hundred tutorials online, there is no mode involved. I even searched something like "azure-cli webapp site" to see if it got renamed or something.

When searching for the `azure site` command, only Microsoft Azure members are aware of such a thing called `mode`.

**Comment by amarzavery** [comment]
@jsgoupil - We completely understand your situation. We shall try to improve the help. Currently, when you execute the help (-h | --help | help) of any command it displays the current mode. May be adding more info about changing the mode (azure config mode asm | azure config mode arm) would help.

Btw, we also have a new python based CLI (which only supports ARM (Version V2 of the Azure API) based services over [here](https://github.com/Azure/azure-cli). This CLI is in public preview right now.

**Comment by balajikris** [comment]
We recently made an improvement here (see PR https://github.com/Azure/azure-xplat-cli/pull/3424) that will ship in the next release `0.10.9`. The fix we made improves the error message when a command is not recognized by the CLI - we determine the current mode the CLI is in and hint to the user that this _could be_ a valid command in the other mode (asm/arm). 

**Here is a screenshot:**
![image](https://cloud.githubusercontent.com/assets/4213867/21868487/c0666060-d807-11e6-93b3-2db83ead964c.png)

Do note that this change simply makes the help text a bit more friendlier, it does not actually verify if the command is legal under _any_ mode. We believe this hint is sufficient to resolve confusions that arise due to _mode_. 

Please let us know what you think.

**Comment by balajikris** [comment]
Fixed with #3424

**Comment by nabaz** [comment]
for whom still have this issue you can switch mode to asm using command `azure config mode asm` and then you can use azure site command
